### ISSUE TITLE
Deprecation warnings for ClusterRole / ClusterRoleBinding / Ingress

### ISSUE THREAD

**Issue by lerminou** [temporalio/helm-charts#115]
Hi, I'm running kubernetes 1.19 with RKE and when i'm installing the chart, These deprecations appears:

```
W1208 21:07:40.172608  495469 warnings.go:67] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W1208 21:07:40.589121  495469 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W1208 21:07:40.644555  495469 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
```

1.22 is scheduled for mid 2021

**Comment by 24601** [comment]
> This appears to be currently causing installation to fail?

Yes, on 1.22 it seems to be.

**Comment by jasoncwik** [comment]
Maybe change the title to `Kubernetes 1.22 support`? :)

Also note that there's a new warning for PDB:

```
W0209 18:20:45.140203   43895 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
```

**Comment by jasoncwik** [comment]
Per my investigation, this was caused by a few things:
* Ingress was using the unsupported v1beta1 version in web-ingress.yaml
* An old version of Prometheus was causing the ClusterRoleBinding errors
* PDB created by ES was also out of date (warning for 1.25)

There still remains one PDB issue caused by Grafana, but we have about 6-9 months before 1.25 and will have to wait on them.
