### ISSUE TITLE
Docker image tag for Web component is not pinned

### ISSUE THREAD

**Issue by thjwhite** [temporalio/helm-charts#319]
### Is your feature request related to a problem? Please describe.

In a recent change for the web UI component it looks like the docker image tag was changed to be "latest" rather than a pinned docker tag. Unfortunately this brings in an opportunity for unexpected behavior / bugs without an explicit deployment. For example a pod may get deleted and pull in a newer version which may change behavior or have bugs. I am not sure if there was any reason for the latest tag so wanted to bring it up to the team.

### Describe the solution you'd like

Change the values.yaml "web.image.tag" to be a pinned version.

### Additional context

This morning we ran into the issue referenced in this linked patch release relating to CSS/JS files not loading. If the versions were pinned it would greatly help us reduce unexpected changes in the UI component of Temporal and allow us to upgrade when we have time to validate the deployment.
https://github.com/temporalio/ui-server/releases/tag/v2.6.1

**Comment by deltamualpha** [comment]
Agreed with the need to pin the ui container tag here. Even setting aside the unexpected-upgrades point, if you change `replicaCount` to anything > 1, new k8s nodes that have the UI container scheduled onto them will pull the newest version of the ui-server container (because of `pullPolicy: IfNotPresent`), which serves different assets from existing running containers. This immediately breaks the UI entirely, as assets are not stable across releases.

**Comment by robholland** [comment]
Long since fixed.
